---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
  namespace: test1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harness
  template:
    metadata:
      labels:
        app: harness
    spec:
      containers:
        - name: newharness
          image: aeon11/harness:1.0
          ports:
            - containerPort: 7000
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: test1svc
  namespace: test1
spec:
  selector:
    app: harness
  ports:
    - port: 80
      targetPort: 7000
  type: NodePort
